let arr= [
    {
      "name":"sid",
      "age":23,
      "location":"naded",
      "nationality":"Indian"
    },
    {
      "name":"sid",
      "age":23,
      "location":"naded",
      "nationality":"Indian"
    },
    {
      "name":"sid",
      "age":23,
      "location":"naded",
      "nationality":"Indian"
    },
    {
      "name":"sid",
      "age":23,
      "location":"naded",
      "nationality":"Indian"
    },
]